### ISSUE TITLE
Mannequin / 'Add' fails

### ISSUE THREAD

**Issue by Oops19** [Oops19/TS4-CopyOutfits#5]
After starting the game with no outfit in the buffer/cache the 'Add' interaction fails. Sometimes a mannequin is spawned with this exception:

Traceback (most recent call last):
  File "T:\InGame\Gameplay\Scripts\Core\sims4\commands.py", line 399, in invoke_command
  File "T:\InGame\Gameplay\Scripts\Server\server_commands\interaction_commands.py", line 989, in select_choice
  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 263, in select_interaction
  File "T:\InGame\Gameplay\Scripts\Server\interactions\choices.py", line 254, in select
  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 243, in test_and_execute
  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 224, in execute
  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 186, in execute_interaction
  File "sims4communitylib\classes\interactions\common_immediate_super_interaction.py", line 244, in _trigger_interaction_start_event
  File "copy_outfits\pie\interactions.py", line 42, in on_started
  File "copy_outfits\main.py", line 120, in on_started
  File "sims4communitylib\utils\common_log_registry.py", line 238, in error
  File "copy_outfits\main.py", line 111, in on_started
  File "copy_outfits\copy_outfits_mannequin.py", line 60, in change_mannequin
  File "copy_outfits\copy_outfits_mannequin.py", line 199, in add_mannequin
  File "copy_outfits\outfit_skin.py", line 110, in apply_skin
  File "sims4communitylib\services\sim\cas\common_sim_outfit_io.py", line 314, in apply
AttributeError: 'NoneType' object has no attribute 'outfit_id'
Error ''NoneType' object has no attribute 'outfit_id''

**Comment by Oops19** [comment]
fixed in v1.9.22
    CO-14 Fix 'Add Mannequin' if no outfits are in buffer
